// Generated by `supabase gen types typescript --project-id $SUPABASE_PROJECT_REF`.
// This file is regenerated in Plan 05 after the schema migration is pushed.
// Do not edit by hand.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
